# cmake-format style configuration
# Reference: https://cmake-format.readthedocs.io/en/latest/config-options.html
format:
  line_width: 100
  tab_size: 4
  use_tabchars: false
  max_subgroups_hwrap: 2
  max_pargs_hwrap: 4
  dangle_parens: false
  separate_ctrl_name_with_space: true
  separate_fn_name_with_space: false
  space_before_paren: false
  autosort: true
  require_valid_layout: false
markup:
  enable_markup: false
parse:
  additional_commands: {}
