# Server runtime configuration
version: 1
max_players_per_match: 16
max_parallel_matches: 8
queue_soft_limit: 256
fill_timeout_seconds: 180  # after this waiting match fills with bots
tick_rate: 30
snapshot_interval_ticks: 5  # every 5 ticks send incremental snapshot (runtime configurable)
full_snapshot_interval_ticks: 30  # send a full snapshot at least this often
bot_difficulty: 1  # 0 = dummy, 1 = basic
listen_port: 40000
heartbeat_timeout_seconds: 30
matchmaker_poll_ms: 200
log_level: info  # debug|info|warn|error
log_json: false  # true to emit JSON lines
metrics_port: 9100  # 0 disables metrics HTTP endpoint (/metrics)
auth_mode: stub     # disabled|stub (future: oauth)
auth_stub_prefix: user_
