# Server runtime configuration
version: 1
max_players_per_match: 4
max_parallel_matches: 8
queue_soft_limit: 256
fill_timeout_seconds: 5    # after this waiting match fills with bots (reduced for faster local matches)
tick_rate: 30
snapshot_interval_ticks: 5  # every 5 ticks send incremental snapshot (runtime configurable)
full_snapshot_interval_ticks: 30  # send a full snapshot at least this often
bot_difficulty: 1  # 0 = dummy, 1 = basic
bot_fire_interval_ticks: 60  # bots fire every N ticks (default 60 -> ~2s at 30Hz)
movement_speed: 2.0           # units per second for tanks
projectile_damage: 25         # damage per projectile hit
reload_interval_sec: 3.0      # seconds to grant +1 ammo (per tank) up to max
projectile_speed: 5.0         # projectile linear speed units/s
projectile_density: 0.01      # physics density for projectile (mass scaling)
hull_density: 1.0             # physics density for tank hull (overall mass)
turret_density: 0.5           # physics density for turret body (affects inertia & rotation feel)
disable_bot_fire: false       # when true bots never fire (can also use --no-bot-fire or env T2D_NO_BOT_FIRE=1)
listen_port: 40000
heartbeat_timeout_seconds: 30
matchmaker_poll_ms: 200
log_level: info  # debug|info|warn|error
log_json: false  # true to emit JSON lines
metrics_port: 9100  # 0 disables metrics HTTP endpoint (/metrics)
auth_mode: stub     # disabled|stub (future: oauth)
auth_stub_prefix: user_
