# S2 scenario config: 2 human placeholders + 20 bots equivalent load
version: 1
max_players_per_match: 22
max_parallel_matches: 2
queue_soft_limit: 256
fill_timeout_seconds: 2
tick_rate: 60
snapshot_interval_ticks: 2
full_snapshot_interval_ticks: 60
bot_difficulty: 1
bot_fire_interval_ticks: 60
movement_speed: 5.0
projectile_damage: 25
reload_interval_sec: 3.0
fire_cooldown_sec: 1.0
projectile_speed: 50.0
projectile_density: 20.0
projectile_max_lifetime_sec: 5.0
hull_density: 1.0
turret_density: 0.5
disable_bot_fire: false
test_mode: false
listen_port: 40002
heartbeat_timeout_seconds: 30
matchmaker_poll_ms: 200
log_level: info
log_json: false
metrics_port: 9101
auth_mode: stub
auth_stub_prefix: user_
map_width: 100
map_height: 100
force_line_spawn: false
persist_destroyed_tanks: true
track_break_hits: 1
turret_disable_front_hits: 2
