name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev cmake g++ ninja-build
      - name: Configure (server + tests + desktop client)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DT2D_BUILD_TESTS=ON -DT2D_BUILD_CLIENT=ON
      - name: Build all
        run: cmake --build build --parallel
      - name: Run tests (ctest)
        working-directory: build
        run: ctest --output-on-failure -T Test
      - name: Upload server binary
        uses: actions/upload-artifact@v4
        with:
          name: t2d_server-linux-amd64
          path: build/t2d_server
          if-no-files-found: error
      - name: Upload desktop client prototype
        uses: actions/upload-artifact@v4
        with:
          name: t2d_desktop_client-linux-amd64
          path: build/t2d_desktop_client
          if-no-files-found: error
